### PR TITLE
Fix misleading error message for invalid annotation format 

### LINKED ISSUE #46: Misleading error message for invalid annotation format
### What happened?

When adding annotation to make resource ready (based on README example):

```yaml
 gotemplating.fn.crossplane.io/ready: True
```

I am getting an error:

```
crossplane: error: cannot render composite resource: pipeline step "render-templates" returned a fatal result: "User" template is missing required "gotemplating.fn.crossplane.io/composition-resource-name" annotation
```

This is misleading because I have set`gotemplating.fn.crossplane.io/composition-resource-name` annotation, and the real error is caused by an invalid format of `ready` annotation (boolean instead of string). It works when I change it to:

```yaml
 gotemplating.fn.crossplane.io/ready: "True"
```

### What environment did it happen in?
Function version: 0.3.0

### PR DESCRIPTION
**Pull request by jtucci**
### Description of your changes
Adds validation to ensure all annotations follow a valid format before proceeding with further processing

Fixes #46 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] Added or updated unit tests for my change.

[contribution process]: https://git.io/fj2m9
[docs]: https://docs.crossplane.io/contribute/contribute

### CODE REVIEW

File: fn.go [hunk 1]
```diff
@@ -105,6 +105,14 @@ func (f *Function) RunFunction(_ context.Context, req *fnv1beta1.RunFunctionRequ
 			response.Fatal(rsp, errors.Wrap(err, "cannot decode manifest"))
 			return rsp, nil
 		}
+		// When decoding YAML into an Unstructured object, unquoted values like booleans or integers
+		// can inadvertently be set as annotations, leading to unexpected behavior in later processing
+		// steps that assume string-only values, such as GetAnnotations.
+		if _, _, err := unstructured.NestedStringMap(u.Object, "metadata", "annotations"); err != nil {
+			response.Fatal(rsp, errors.Wrap(err, "invalid function input: invalid %v"))
```
Comment (phisco) [inline fn.go:112]: Looks like you either wanted to use WrapF and pass the invalid annotation and value, or you left a dangling %v. Either way, I think it would be better to have a more explicit message here, e.g. `invalid annotations`, mentioning the resource gvk and either the resource name set via the given annotation or the metadata.name, if any of them is available.

Comment (jtucci) [reply fn.go]: Example of the error message when rendering the 'inline' example with an invalid value of True set would now be:

`crossplane: error: cannot render composite resource: pipeline step "render-templates" returned a fatal result: invalid annotations in resource "iam.aws.upbound.io/v1beta1, Kind=User": .metadata.annotations accessor error: contains non-string key in the map: true is of the type bool, expected string`

It might be a little harder to include the resource name thats set via annotation since the function used to retrieve it (GetAnnotations) is the point of failure. Do you think this message is explicit enough, or should I also include the metadata.name if it exists?

Comment (phisco) [reply fn.go]: Looking good now, thanks 🙏

**Review by phisco — APPROVED** [review]

**Comment by ravilr** [comment]
Ah, we forgot to update the README.md with quoted `gotemplating.fn.crossplane.io/ready: "True"` ?, which folks seem to follow/copy and run into this issue..

**Comment by phisco** [comment]
> Ah, we forgot to update the README.md with quoted `gotemplating.fn.crossplane.io/ready: "True"` ?, which folks seem to follow/copy and run into this issue...

Good catch! Fixed now! 🙏
